export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE';

export const OBTENER_NUEVO_P = 'OBTENER_NUEVO_P';
export const OBTENER_CARRITO = 'OBTENER_CARRITO';
export const OCULTAR_NUEVO_P = 'OCULTAR_NUEVO_P';
export const OCULTAR_CARRITO = 'OCULTAR_CARRITO';

export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_IMAGENES = 'OBTENER_IMAGENES';
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';
export const BORRAR_PRODUCTO = 'BORRAR_PRODUCTO';
