export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const LIMPIAR_MENSAJE = 'LIMPIAR_MENSAJE';

export const OBTENER_NUEVO_P = 'OBTENER_NUEVO_P';
export const OBTENER_CARRITO = 'OBTENER_CARRITO';
export const OCULTAR_NUEVO_P = 'OCULTAR_NUEVO_P';
export const OCULTAR_CARRITO = 'OCULTAR_CARRITO';